name: "Publish Plugin Packages"

# This workflow is triggered only when a new tag matching the pattern 'v*.*.*' is pushed.
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-crate-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo publish dry-run
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: true

  publish-npm-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Build the plugin
        run: pnpm build
      - name: Run npm publish dry-run
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true

  publish-crate:
    needs: [publish-crate-dry-run, publish-npm-dry-run]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-npm:
    needs: [publish-crate-dry-run, publish-npm-dry-run]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Build the plugin
        run: pnpm build
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
